/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCardHeader: typeof import('bootstrap-vue-next')['BCardHeader']
    BCardText: typeof import('bootstrap-vue-next')['BCardText']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BDiv: typeof import('bootstrap-vue-next')['BDiv']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Homepage: typeof import('./src/components/Homepage.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBToggle: typeof import('bootstrap-vue-next')['vBToggle']
  }
}
